GET https://localhost:8080/task
###
POST https://localhost:8080/task
content-type: application/json

{
    "text": "adminov task",
    "tags": []
}
###
DELETE https://admin:adminkooo@localhost:8080/task/16
###
GET https://localhost:8080/health
###
POST https://admin:adminkooo@localhost:8080/register
content-type: application/json

{
    "name": "admin",
    "pass": "adminkooo"
}
###
POST https://localhost:8080/login
content-type: application/json

{
    "name": "admin",
    "pass": "adminkooo"
}
###
POST https://localhost:8080/logout
