GET https://localhost:8080/task
###
POST https://admin:adminkooo@localhost:8080/task
content-type: application/json

{
    "text": "adminov task",
    "tags": []
}
###
GET https://localhost:8080/tag/todo
###
DELETE https://admin:adminkooo@localhost:8080/task/11
###
GET https://localhost:8080/health
###
POST https://admin:adminkooo@localhost:8080/register
content-type: application/json

{
    "name": "admin",
    "pass": "adminkooo"
}